import { textStyles } from '../../src/primitives/textStyles';
/**
 * The text style format generated by generateTextStyles does not support the stitches format.
 * This helper takes the text style format and converts it to the stitches format.
 *
 * @param styleName The name of the style to convert
 */

export const getStitchesTextStyle = (styleName: string) => {
  const split = styleName.split(':');
  const name = split[0];
  const style = split[1];
  const textStyle = textStyles[name][style];

  return textStyle;
};
