import { textStyles } from '../../src/primitives/textStyles';
/**
 * The text style format generated by generateTextStyles does not support the stitches format.
 * This helper takes the text style format and converts it to the stitches format.
 *
 * @param value The name of the text style to convert, must be a string containing the name and style delimited by a ':'
 */

export const getStitchesTextStyle = (value: string) => {
  const split = value.split(':');

  if (split[0] && split[1]) {
    const name = split[0];
    const style = split[1];
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const textStyle = (textStyles as any)[name][style];

    return textStyle;
  }

  return undefined;
};
